title: Eric Chen's Notes
description: Eric Chen's notes on things.

theme: just-the-docs
color_scheme: ec-light

url: https://notes.ericgtkb.com

markdown: kramdown

# Compressing html causes issues with code block with linenos
compress_html:
  ignore:
    envs: all

favicon_ico: /assets/images/logo.svg

plugins:
  - jekyll-scholar

scholar:
  style: apa
