title: Eric Chen's Notes
description: Eric Chen's notes on things.

theme: just-the-docs
color_scheme: ec-light

url: https://ericgtkb.github.io
baseurl: /notes

markdown: kramdown

favicon_ico: /assets/images/logo.svg

plugins:
  - jekyll-scholar

scholar:
  style: apa
